#!/usr/bin/env python3
"""
Build a single self-contained preview.html.

The real site fetches data/*.json at runtime, which browsers block on file://
URLs. This script inlines the CSS, the JS and all five data files into one
file you can double-click. It is a preview only — the deployed site is the
real pages plus scripts/build.py. Regenerate any time with:

    python3 scripts/preview.py
"""

import base64
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

css = (ROOT / "assets" / "style.css").read_text(encoding="utf-8")
js = (ROOT / "assets" / "app.js").read_text(encoding="utf-8")
data = {n: json.loads((ROOT / "data" / f"{n}.json").read_text(encoding="utf-8"))
        for n in ("site", "research", "people", "publications", "news", "sponsors")}
favicon = base64.b64encode((ROOT / "assets" / "favicon.png").read_bytes()).decode()
logo = (ROOT / "assets" / "logo.svg").read_text(encoding="utf-8")

BOOTSTRAP = """
// Preview shim: seed the data cache so load() never fetches, and turn the
// header links into in-page page switches instead of navigations.
Object.assign(DATA, window.__PEARL_DATA__);

const PAGES = ['index.html', 'research.html', 'people.html', 'publications.html', 'news.html'];

function show(page) {
  document.querySelector('main').innerHTML = {
    'index.html': '<section class="hero" id="hero"></section><section id="thrusts"></section><section id="latest"></section>',
    'research.html': '<section id="research" style="border:0"></section>',
    'people.html': '<section id="people" style="border:0"></section>',
    'publications.html': '<section id="publications" style="border:0"></section>',
    'news.html': '<section id="news" style="border:0"></section>',
  }[page];
  boot(page);
  window.scrollTo(0, 0);
}

document.addEventListener('click', (e) => {
  const a = e.target.closest('a');
  if (!a) return;
  const href = a.getAttribute('href') || '';
  if (href.startsWith('http') || href.startsWith('mailto:')) return;
  const page = href.split('#')[0].split('/').pop();
  if (PAGES.includes(page)) { e.preventDefault(); show(page); return; }
  // News permalinks (news/<slug>/) do not exist in the preview -> jump to the list.
  if (href.includes('news/')) {
    e.preventDefault();
    const slug = href.replace(/\\/$/, '').split('/').pop();
    show('news.html');
    setTimeout(() => {
      const t = document.getElementById(slug);
      if (t) t.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }, 60);
    return;
  }
  if (href === 'feed.xml' || href.endsWith('/feed.xml')) {
    e.preventDefault();
    alert('feed.xml is generated by scripts/build.py when the site is deployed.');
  }
});

show('index.html');
"""

BANNER = """<div style="background:var(--bg-alt);border-bottom:1px solid var(--line);
  padding:9px 0;font-size:.82rem;color:var(--muted);text-align:center">
  Offline preview of the PEARL Lab site &mdash; all five pages, real content.
  Navigation works; news permalinks and the RSS feed only exist once deployed.
</div>"""

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PEARL Lab &mdash; preview</title>
<link rel="icon" href="data:image/png;base64,{favicon}">
<style>
{css}
</style>
</head>
<body>
{BANNER}
<header class="site" id="site-header"></header>
<main id="main"></main>
<footer class="site" id="site-footer"></footer>
<script>window.__PEARL_DATA__ = {json.dumps(data)};</script>
<script>window.__PEARL_LOGO__ = {json.dumps(logo)};</script>
<script>
{js}
{BOOTSTRAP}
</script>
</body>
</html>
"""

out = ROOT / "preview.html"
out.write_text(html, encoding="utf-8")
print(f"wrote {out} ({len(html) // 1024} KB)")
